 var points = [
 	{id:a1 ,
 		city: "Waipahu"},
 	{id:a2,
 		city:"Pearl City" },
 	{id:a3,
 		city:"Waimalu" },
 	{id:a4,
 		city:"" },
 	{id:a5,
 		city:"" },
 	{id:a6,
 		city:"" },
 	{id:a7,
 		city:"" },
 	{id:a8,
 		city:"" },
 	{id:a9,
 		city:"" },
 	{id:a10,
 		city:"" },
 	{id:a11,
 		city:"" },
 	{id:a12,
 		city:"" },
 	{id:a13,
 		city:"" },
 	{id:a14,
 		city:"" },
 	{id:a15,
 		city:"" },
 	{id:a16,
 		city:"" },
 	{id:a17,
 		city:"" },
 	{id:a18,
 		city:"" },
 	{id:a19,
 		city:"" },
 	{id:a20,
 		city:"" },
 	{id:a21,
 		city:"" },
 	{id:a22,
 		city:"" },
 	{id:a23,
 		city:"" },
 	{id:a24,
 		city:"" },
 	{id:a25,
 		city:"" },
 	{id:a26,
 		city:"" },
 	{id:a27,
 		city:"" },
 	{id:a28,
 		city:"" },
 	{id:a29,
 		city:"" },
 	{id:a30,
 		city:"" },
 	{id:a31,
 		city:"" },
 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	 	
]
console.log(points)
var currentCity = null;
function showData(city){
	//document.getElementById(currentCity).style.display = "none"
	document.getElementById(city).style.display="block"
	currentCity = city;
}
function hideCity(currentCity){
	document.getElementById(currentCity).style.display = "none"
}